#!/bin/sh
set -e

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

mount -t devtmpfs devtmpfs /dev

mkdir -p /var/log
syslogd
sleep 1
logger -s -p user.info -t "init[$$]" "Start init"

mkdir -p /dev/pts

logger -s -p user.info -t "init[$$]" "Mounting system"
mount -t devpts devpts /dev/pts
mount -t proc none /proc
mount -t tmpfs none /run
mount -t sysfs none /sys
mount -t tmpfs none /sys/fs/cgroup

for i in blkio cpu cpuacct cpuset devices freezer memory net_cls perf_event; do
  mkdir -p /sys/fs/cgroup/$i
  mount -t cgroup -o $i none /sys/fs/cgroup/$i
done

# Basic Configuration
# from https://github.com/rancherio/os/blob/master/scripts/dockerimages/00-base
sed -i '/^root/s!/bin/sh!/bin/bash!' /etc/passwd
echo 'RancherOS Lite: \n \l' > /etc/issue
passwd -l root
addgroup -g 1100 rancher
addgroup -g 1101 docker
addgroup -g 1103 sudo
adduser -u 1100 -G rancher -D -h /home/rancher -s /bin/bash rancher
sed -i 's/\(^docker.*\)/\1rancher/g' /etc/group
sed -i 's/\(^sudo.*\)/\1rancher/g' /etc/group
echo '%sudo ALL=(ALL) ALL' >> /etc/sudoers

# from https://github.com/rancherio/os/blob/master/scripts/dockerimages/06-console
sed -i 's/rancher:!/rancher:*/g' /etc/shadow
echo '## allow password less for rancher user' >> /etc/sudoers
echo 'rancher ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Setup consistent volumes
mkdir -p /var/lib/docker
mkdir -p /var/lib/rancheros-lite

DEVICE=$(blkid | grep -e 'LABEL="RANCHEROS-DATA"' | head -n 1 | sed 's/:.*//')
if [ -n "$DEVICE" ]; then
  PARTNAME=$(echo "$DEVICE" | sed 's/.*\///')
  logger -s -p user.info -t "init[$$]" "Mounting HDD /dev/$PARTNAME"
  mkdir -p /mnt/$PARTNAME
  if ! mount -t ext4 /dev/$PARTNAME /mnt/$PARTNAME; then
    logger -s -p user.info -t "init[$$]" "Running from memory, this won't be good..."
  else
    rm -rf /var/lib/docker
    mkdir -p /mnt/$PARTNAME/var/lib/docker
    ln -s /mnt/$PARTNAME/var/lib/docker /var/lib/docker

    rm -rf /var/lib/rancheros-lite
    mkdir -p /mnt/$PARTNAME/var/lib/rancheros-lite
    ln -s /mnt/$PARTNAME/var/lib/rancheros-lite /var/lib/rancheros-lite
  fi

  # from https://github.com/rancherio/os/blob/master/scripts/dockerimages/scripts/udev.sh
  udevd --daemon
  udevadm trigger --action=add
  udevadm settle
fi
DEVICE=$(blkid | grep -e 'LABEL="RANCHEROS-SWAP"' | head -n 1 | sed 's/:.*//')
if [ -n "$DEVICE" ]; then
  logger -s -p user.info -t "init[$$]" "Enable SWAP $DEVICE"
  swapon $DEVICE
else
  DEVICE=$(ls -l /dev/disk/by-label | grep -e RANCHEROS-SWAP | head -n 1 | cut -f 3 -d '/')
  if [ -n "$DEVICE" ]; then
    logger -s -p user.info -t "init[$$]" "Enable SWAP /dev/$DEVICE"
    swapon /dev/$DEVICE
  fi
fi

logger -s -p user.info -t "init[$$]" "Configuring Network"
echo "rancheros-lite" > /etc/hostname
hostname -F /etc/hostname

cat <<EOF > /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
options single-request-reopen
EOF

ifconfig lo 127.0.0.1
udhcpc -i eth0

logger -s -p user.info -t "init[$$]" "Configuring SSH"
mkdir -p /etc/ssh
if [ ! -d /var/lib/rancheros-lite/ssh ]; then
  mv /etc/ssh /var/lib/rancheros-lite/ssh
else
  rm -rf /etc/ssh
fi
ln -s /var/lib/rancheros-lite/ssh /etc/ssh

for i in rsa dsa ecdsa ed25519; do
  output=/etc/ssh/ssh_host_${i}_key
  if [ ! -f $output ]; then
    ssh-keygen -t $i -f $output -N '' > /dev/null
  fi
done

# Disable SSH Password Authentication
if ! grep -q "^PasswordAuthentication no" /etc/ssh/sshd_config; then
  echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
fi

# Disable SSH Use DNS
if ! grep -q "^UseDNS no" /etc/ssh/sshd_config; then
  echo "UseDNS no" >> /etc/ssh/sshd_config
fi

/usr/sbin/sshd

logger -s -p user.info -t "init[$$]" "Configuring for Vagrant"
mkdir -p /home/rancher
if [ ! -d /var/lib/rancheros-lite/rancher ]; then
  mv /home/rancher /var/lib/rancheros-lite/rancher
else
  rm -rf /home/rancher
fi
ln -s /var/lib/rancheros-lite/rancher /home/rancher
chown rancher:rancher /home/rancher
mkdir -p /home/rancher/.ssh
chmod 0700 /home/rancher/.ssh

if [ ! -f /home/rancher/.ssh/authorized_keys ]; then
  cat <<KEY >/home/rancher/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
KEY
  chmod 0600 /home/rancher/.ssh/authorized_keys
fi
chown -R rancher:rancher /home/rancher/.ssh

sync

logger -s -p user.info -t "init[$$]" "Starting console"
openvt -s -l bash

if [ -f /var/lib/rancheros-lite/profile ]; then
  logger -s -p user.info -t "init[$$]" "Reloading /var/lib/rancheros-lite/profile"
  source /var/lib/rancheros-lite/profile
fi

if [ -z "$DOCKER_STORAGE" ]; then
  DOCKER_STORAGE="overlay"
fi
if [ -z "$DOCKER_DIR" ]; then
  DOCKER_DIR="/var/lib/docker"
fi
if [ -z "$DOCKER_HOST" ]; then
  DOCKER_HOST="-H unix:// -H tcp://0.0.0.0:2375"
fi

logger -s -p user.info -t "init[$$]" "Starting Docker -d -D -s $DOCKER_STORAGE -g \"$DOCKER_DIR\" $DOCKER_HOST $DOCKER_EXTRA_ARGS"
# Top secret option...
export DOCKER_RAMDISK=true
exec docker -d -D -s $DOCKER_STORAGE -g "$DOCKER_DIR" $DOCKER_HOST $DOCKER_EXTRA_ARGS
