#!/bin/sh
set -e

CONTAINERS="$(docker ps -q)"
CONTAINERS=$(echo ${CONTAINERS})
if [ -n "${CONTAINERS}" ]; then
  logger -s -p user.info -t "$(basename $0)[$$]" "Stopping containers"
  docker stop -t 2 ${CONTAINERS}
fi

CMD=$(basename $0)
ARGS="$@"
if [ "${CMD}" == "shutdown" ]; then
  CMD="poweroff"
  ARGS=""
  while getopts ":r" opt; do
    case $opt in
      r)
        CMD="reboot"
        ;;
    esac
  done
fi
logger -s -p user.info -t "$(basename $0)[$$]" "${CMD}"
setsid busybox ${CMD} -f -d 1 ${ARGS} &

#logger -s -p user.info -t "$(basename $0)[$$]" "Terminating SSH connections"
killall sshd
